### PR TITLE
Add :barh to Gruff

### PR DESCRIPTION
**Pull request by yaboojp**
"p.labels" is required, therefore set nil to "p.labels".
But I'm wondering if such a solution is good??

```
charty = Charty::Plotter.new(:gruff)
bar = charty.barh do
  series [0,1,2,3,4], label: "sample1"
  series [0,1,2,3,4], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/barh_gruff.png")
```
image

### CODE REVIEW

**Comment by 284km** [comment]
I examined a little and understood.
labels is required with SideBar as follows.

https://www.rubydoc.info/github/topfunky/gruff/Gruff/Base#labels-instance_method

I think that `p.labels = {nil=>nil}` is good as the first step. In this case, labael is not displayed like this.

graph_no_label

For example, when a label is set, it is displayed like this. I think it would be better if we could support `label` as well.

```ruby
# e.g.

require 'gruff'
p = Gruff::SideBar.new
p.title = "sample title"
p.x_axis_label = "x label"
p.y_axis_label = "y label"
p.data(data.label, data.xs.to_a)
p.data("sample1", [0,1,2,3,4])
p.data("sample2", [0,1,2,3,4])
p.data("sample3", [0,1,2,3,4,5,6,7,8])
p.labels = {0 => "label0", 1 => "label1", 2 => "label2", 5 => "label5", 8 => "label8", 9 => "label9"}
p.write
```

graph

**Comment by yaboojp** [comment]
I've modified that each series has specified a label.
This graph image is different from other graphs, but I think this is natural for Gruff.

```
charty = Charty::Plotter.new(:gruff)

bar = charty.barh do
  series ["sample1","sample2","sample3"], [1,2,3], label: "label-1"
  series ["sample1","sample2","sample3"], [4,5,6], label: "label-2"
  series ["sample1","sample2","sample4"], [2,3,4], label: "label-3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end

bar.render("barh_gruff.png")
```
image

**Comment by yaboojp** [comment]
I've modified that each series has specified a label.
This graph image is different from other graphs, but I think this is natural for Gruff.

```
charty = Charty::Plotter.new(:gruff)

bar = charty.barh do
  series ["sample1","sample2","sample3"], [1,2,3], label: "label-1"
  series ["sample1","sample2","sample3"], [4,5,6], label: "label-2"
  series ["sample1","sample2","sample4"], [2,3,4], label: "label-3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end

bar.render("barh_gruff.png")
```
image

**Comment by 284km** [comment]
Thanks! I confirmed the output image. Looks good. I will merge it.

**Pull request merged**
