### PR TITLE
Add google charts backend

### PR DESCRIPTION
**Pull request by indigolain**
I would like to add Google Charts support as the backend rendering engine in Charty.

I'm in the middle of implementing a bar graph feature with google charts, and want to know if I'm going in the right direction. I especially want to know if there is any thoughts in how the `#render` and `#plot` methods are supposed to behave with javascript type backend.

### CODE REVIEW

**Comment by 284km** [comment]
I examined a little about Google Charts. I confirmed plotting the graph of Google Charts with this code.

google_charts

I think this direction is good. But unfortunately at the moment there is nothing I can advise about JavaScript backend. Because there is no JavaScript backend implementation yet.

**Comment by indigolain** [comment]
@284km 
Thank you for the review! 
If I am going in the right direction with this implementation, can this pull request be merged after migrating to the new abstracted plotter implementation that was introduced from this? 
https://github.com/red-data-tools/charty/pull/13

**Comment by 284km** [comment]
Yes, I want to do that.

In addition to Bar Chart, are there other chart types that you  will implement in Google Charts?

refs.
https://developers.google.com/chart/interactive/docs/gallery

**Comment by indigolain** [comment]
> In addition to Bar Chart, are there other chart types that you will implement in Google Charts?

I would love to implement scatter and bubble charts as well. Should I split these implementations in a new pull request or should I include them to this pull request?

**Comment by 284km** [comment]
Great! It would be nice if you could include them in this pull request.
But if it takes time, you can create a new pull request.

**Comment by indigolain** [comment]
@284km 
I'm done implementing scatter and bubble charts! Could you check them?

スクリーンショット 2019-05-22 8 58 09
スクリーンショット 2019-05-22 8 58 19

**Comment by 284km** [comment]
Thanks! I will merge it.

**Comment by indigolain** [comment]
@284km 
Thank you!

**Pull request merged**
